name: async_downloader
description: "A New Flutter Project"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  http: ^1.3.0
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  path: ^1.9.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true